import { BaseSeeder } from '@adonisjs/lucid/seeders'
import VoucherDiskon from '#models/voucher_diskon'
import { nanoid } from 'nanoid'
import { DateTime } from 'luxon'

export default class extends BaseSeeder {
  async run() {
    await VoucherDiskon.createMany([
      {
        nama: 'Diskon Belanja Shopee 10RB',
        merchant: 'Shopee',
        description: 'Diskon Rp10.000 untuk semua produk minimal belanja Rp50.000',
        nominal: 10000,
        price: 5000,
        kode_voucher: nanoid(10),
        expired_at: DateTime.now().plus({ days: 30 }),
        is_sold: false,
      },
      {
        nama: 'Diskon Gojek 15RB',
        merchant: 'Gojek',
        description: 'Voucher diskon Rp15.000 untuk layanan GoFood min pembelian Rp60.000',
        nominal: 15000,
        price: 8000,
        kode_voucher: nanoid(10),
        expired_at: DateTime.now().plus({ days: 30 }),
        is_sold: false,
      },
      {
        nama: 'Diskon Tokopedia 20RB',
        merchant: 'Tokopedia',
        description: 'Potongan Rp20.000 untuk transaksi elektronik',
        nominal: 20000,
        price: 10000,
        kode_voucher: nanoid(10),
        expired_at: DateTime.now().plus({ days: 20 }),
        is_sold: false,
      },
      {
        nama: 'Diskon Grab 12RB',
        merchant: 'Grab',
        description: 'Diskon layanan GrabFood senilai Rp12.000',
        nominal: 12000,
        price: 6000,
        kode_voucher: nanoid(10),
        expired_at: DateTime.now().plus({ days: 15 }),
        is_sold: false,
      },
      {
        nama: 'Diskon Alfamart 5%',
        merchant: 'Alfamart',
        description: 'Diskon 5% untuk semua pembelian',
        nominal: 5000,
        price: 3000,
        kode_voucher: nanoid(10),
        expired_at: DateTime.now().plus({ days: 45 }),
        is_sold: false,
      },
      {
        nama: 'Diskon Indomaret 10%',
        merchant: 'Indomaret',
        description: 'Diskon 10% khusus produk rumah tangga',
        nominal: 10000,
        price: 5000,
        kode_voucher: nanoid(10),
        expired_at: DateTime.now().plus({ days: 25 }),
        is_sold: false,
      },
      {
        nama: 'Diskon Zalora 25RB',
        merchant: 'Zalora',
        description: 'Diskon Rp25.000 untuk fashion wanita',
        nominal: 25000,
        price: 15000,
        kode_voucher: nanoid(10),
        expired_at: DateTime.now().plus({ days: 10 }),
        is_sold: false,
      },
      {
        nama: 'Diskon Tokopedia 5%',
        merchant: 'Tokopedia',
        description: 'Diskon 5% untuk semua kategori kecuali emas',
        nominal: 5000,
        price: 2500,
        kode_voucher: nanoid(10),
        expired_at: DateTime.now().plus({ days: 18 }),
        is_sold: false,
      },
      {
        nama: 'Diskon GrabExpress 20RB',
        merchant: 'Grab',
        description: 'Potongan Rp20.000 untuk pengiriman GrabExpress',
        nominal: 20000,
        price: 12000,
        kode_voucher: nanoid(10),
        expired_at: DateTime.now().plus({ days: 20 }),
        is_sold: false,
      },
      {
        nama: 'Diskon ShopeeFood 10%',
        merchant: 'Shopee',
        description: 'Diskon 10% tanpa minimum pembelian',
        nominal: 10000,
        price: 4000,
        kode_voucher: nanoid(10),
        expired_at: DateTime.now().plus({ days: 7 }),
        is_sold: false,
      },
      {
        nama: 'Diskon PLN 30RB',
        merchant: 'PLN',
        description: 'Diskon pembayaran tagihan listrik',
        nominal: 30000,
        price: 18000,
        kode_voucher: nanoid(10),
        expired_at: DateTime.now().plus({ days: 30 }),
        is_sold: false,
      },
      {
        nama: 'Diskon OVO Cashback 5%',
        merchant: 'OVO',
        description: 'Cashback 5% untuk pembayaran dengan OVO',
        nominal: 5000,
        price: 2500,
        kode_voucher: nanoid(10),
        expired_at: DateTime.now().plus({ days: 12 }),
        is_sold: false,
      },
      {
        nama: 'Diskon Dana Rp10.000',
        merchant: 'Dana',
        description: 'Diskon Rp10.000 untuk transaksi digital',
        nominal: 10000,
        price: 5000,
        kode_voucher: nanoid(10),
        expired_at: DateTime.now().plus({ days: 20 }),
        is_sold: false,
      },
      {
        nama: 'Diskon GoPay Rp15.000',
        merchant: 'Gojek',
        description: 'Diskon transaksi min Rp75.000',
        nominal: 15000,
        price: 7500,
        kode_voucher: nanoid(10),
        expired_at: DateTime.now().plus({ days: 10 }),
        is_sold: false,
      },
      {
        nama: 'Diskon Belanja Bukalapak',
        merchant: 'Bukalapak',
        description: 'Voucher diskon Bukalapak untuk semua kategori',
        nominal: 10000,
        price: 6000,
        kode_voucher: nanoid(10),
        expired_at: DateTime.now().plus({ days: 21 }),
        is_sold: false,
      },
    ])
  }
}
