import VoucherListrik from '#models/voucher_listrik'
import { BaseSeeder } from '@adonisjs/lucid/seeders'
import { DateTime } from 'luxon'
import { customAlphabet } from 'nanoid'

const nanoid = customAlphabet('1234567890ABCDEFGHJKLMNPQRSTUVWXYZ', 12)

export default class extends BaseSeeder {
  async run() {
    await VoucherListrik.createMany([
      {
        provider: 'PLN',
        nominal: '100.000',
        price: 95000,
        description: 'Token listrik nominal 100 ribu',
        kode_voucher: nanoid(),
        is_sold: false,
        user_id: null,
        expired_at: DateTime.now().plus({ days: 30 }),
      },
      {
        provider: 'PLN',
        nominal: '50.000',
        price: 48000,
        description: 'Token listrik nominal 50 ribu',
        kode_voucher: nanoid(),
        is_sold: false,
        user_id: null,
        expired_at: DateTime.now().plus({ days: 30 }),
      },
      {
        provider: 'PLN',
        nominal: '20.000',
        price: 19500,
        description: 'Token listrik nominal 20 ribu',
        kode_voucher: nanoid(),
        is_sold: false,
        user_id: null,
        expired_at: DateTime.now().plus({ days: 20 }),
      },
      {
        provider: 'PLN',
        nominal: '200.000',
        price: 190000,
        description: 'Token listrik nominal 200 ribu',
        kode_voucher: nanoid(),
        is_sold: false,
        user_id: null,
        expired_at: DateTime.now().plus({ days: 25 }),
      },
      {
        provider: 'PLN',
        nominal: '500.000',
        price: 475000,
        description: 'Token listrik nominal 500 ribu',
        kode_voucher: nanoid(),
        is_sold: false,
        user_id: null,
        expired_at: DateTime.now().plus({ days: 60 }),
      },
      {
        provider: 'PLN',
        nominal: '10.000',
        price: 9800,
        description: 'Token listrik nominal 10 ribu',
        kode_voucher: nanoid(),
        is_sold: false,
        user_id: null,
        expired_at: DateTime.now().plus({ days: 15 }),
      },
      {
        provider: 'PLN',
        nominal: '75.000',
        price: 72000,
        description: 'Token listrik nominal 75 ribu',
        kode_voucher: nanoid(),
        is_sold: false,
        user_id: null,
        expired_at: DateTime.now().plus({ days: 30 }),
      },
      {
        provider: 'PLN',
        nominal: '300.000',
        price: 285000,
        description: 'Token listrik nominal 300 ribu',
        kode_voucher: nanoid(),
        is_sold: false,
        user_id: null,
        expired_at: DateTime.now().plus({ days: 45 }),
      },
      {
        provider: 'PLN',
        nominal: '30.000',
        price: 29000,
        description: 'Token listrik nominal 30 ribu',
        kode_voucher: nanoid(),
        is_sold: false,
        user_id: null,
        expired_at: DateTime.now().plus({ days: 22 }),
      },
      {
        provider: 'PLN',
        nominal: '400.000',
        price: 385000,
        description: 'Token listrik nominal 400 ribu',
        kode_voucher: nanoid(),
        is_sold: false,
        user_id: null,
        expired_at: DateTime.now().plus({ days: 40 }),
      },
      {
        provider: 'PLN',
        nominal: '150.000',
        price: 142000,
        description: 'Token listrik nominal 150 ribu',
        kode_voucher: nanoid(),
        is_sold: false,
        user_id: null,
        expired_at: DateTime.now().plus({ days: 33 }),
      },
      {
        provider: 'PLN',
        nominal: '25.000',
        price: 24000,
        description: 'Token listrik nominal 25 ribu',
        kode_voucher: nanoid(),
        is_sold: false,
        user_id: null,
        expired_at: DateTime.now().plus({ days: 21 }),
      },
      {
        provider: 'PLN',
        nominal: '600.000',
        price: 570000,
        description: 'Token listrik nominal 600 ribu',
        kode_voucher: nanoid(),
        is_sold: false,
        user_id: null,
        expired_at: DateTime.now().plus({ days: 70 }),
      },
      {
        provider: 'PLN',
        nominal: '750.000',
        price: 712000,
        description: 'Token listrik nominal 750 ribu',
        kode_voucher: nanoid(),
        is_sold: false,
        user_id: null,
        expired_at: DateTime.now().plus({ days: 75 }),
      },
      {
        provider: 'PLN',
        nominal: '1.000.000',
        price: 950000,
        description: 'Token listrik nominal 1 juta',
        kode_voucher: nanoid(),
        is_sold: false,
        user_id: null,
        expired_at: DateTime.now().plus({ days: 90 }),
      },
    ])
  }
}
